import NavBar from "@/components/NavBar";
import HomePage from "@/components/HomePage";
import '../styles/global.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <>
        <html lang="en">
        <body>
            <NavBar />
            {children}
        </body>
        </html>
      </>
  )
}
